# Changes here will be overwritten by Copier
_commit: v3
_src_path: git+https://github.com/WaylonWalker/markata-blog-starter
author_email: nic.payne@avant.com
author_fullname: Nicholas Payne
author_twitter: '@'
description: Blog posts about stuff I work on
project_name: My Working Notes
python_package_import_name: my_working_notes
url: http://localhost:8008

